package com.example.speedcam

import java.util.Locale

/**
 * COCO (80 sınıf) etiketleri seçili uygulama dilinde.
 * Bulunamayan dilde İngilizce döner.
 */
object DetectionLabels {

    fun of(english: String?): String? {
        if (english == null) return null
        val m = mapFor() ?: return english
        return m[english.lowercase(Locale.US)] ?: english
    }

    private fun mapFor(): Map<String, String>? {
        return try {
            val locales =
                androidx.appcompat.app.AppCompatDelegate.getApplicationLocales()
            val tag = if (!locales.isEmpty) locales[0]?.toLanguageTag()
            else Locale.getDefault().toLanguageTag()
            if (tag.isNullOrEmpty()) return null
            ALL[tag] ?: ALL[tag.substringBefore('-')] ?: ALL[tag.substringBefore('_')]
        } catch (_: Exception) { null }
    }

    private val ALL: Map<String, Map<String, String>> by lazy {
        mapOf(
            "tr" to TR,
            "de" to LabelsDe.MAP,
            "fr" to LabelsFr.MAP,
            "es" to LabelsEs.MAP,
            "it" to LabelsIt.MAP,
            "pt" to LabelsPt.MAP,
            "ru" to LabelsRu.MAP,
            "uk" to LabelsUk.MAP,
            "ar" to LabelsAr.MAP,
            "fa" to LabelsFa.MAP,
            "zh-CN" to LabelsZhCN.MAP,
            "zh" to LabelsZhCN.MAP,
            "zh-TW" to LabelsZhTW.MAP,
            "ja" to LabelsJa.MAP,
            "ko" to LabelsKo.MAP,
            "hi" to LabelsHi.MAP,
            "id" to LabelsId.MAP,
            "ms" to LabelsMs.MAP,
            "th" to LabelsTh.MAP,
            "vi" to LabelsVi.MAP,
            "pl" to LabelsPl.MAP,
            "nl" to LabelsNl.MAP,
            "el" to LabelsEl.MAP,
            "he" to LabelsHe.MAP,
            "hu" to LabelsHu.MAP,
            "ro" to LabelsRo.MAP,
            "cs" to LabelsCs.MAP,
            "bg" to LabelsBg.MAP,
            "hr" to LabelsHr.MAP,
            "sr" to LabelsSr.MAP,
            "sv" to LabelsSv.MAP
        )
    }

    private val TR = mapOf(
        "person" to "İnsan",
        "bicycle" to "Bisiklet",
        "car" to "Araba",
        "motorcycle" to "Motosiklet",
        "airplane" to "Uçak",
        "bus" to "Otobüs",
        "train" to "Tren",
        "truck" to "Kamyon",
        "boat" to "Tekne",
        "traffic light" to "Trafik lambası",
        "fire hydrant" to "Hidrant",
        "stop sign" to "Dur tabelası",
        "parking meter" to "Parkmetre",
        "bench" to "Bank",
        "bird" to "Kuş",
        "cat" to "Kedi",
        "dog" to "Köpek",
        "horse" to "At",
        "sheep" to "Koyun",
        "cow" to "İnek",
        "elephant" to "Fil",
        "bear" to "Ayı",
        "zebra" to "Zebra",
        "giraffe" to "Zürafa",
        "backpack" to "Sırt çantası",
        "umbrella" to "Şemsiye",
        "handbag" to "El çantası",
        "tie" to "Kravat",
        "suitcase" to "Bavul",
        "frisbee" to "Frizbi",
        "skis" to "Kayak",
        "snowboard" to "Snowboard",
        "sports ball" to "Top",
        "kite" to "Uçurtma",
        "baseball bat" to "Beyzbol sopası",
        "baseball glove" to "Beyzbol eldiveni",
        "skateboard" to "Kaykay",
        "surfboard" to "Sörf tahtası",
        "tennis racket" to "Tenis raketi",
        "bottle" to "Şişe",
        "wine glass" to "Kadeh",
        "cup" to "Bardak",
        "fork" to "Çatal",
        "knife" to "Bıçak",
        "spoon" to "Kaşık",
        "bowl" to "Kâse",
        "banana" to "Muz",
        "apple" to "Elma",
        "sandwich" to "Sandviç",
        "orange" to "Portakal",
        "broccoli" to "Brokoli",
        "carrot" to "Havuç",
        "hot dog" to "Sosisli",
        "pizza" to "Pizza",
        "donut" to "Donut",
        "cake" to "Pasta",
        "chair" to "Sandalye",
        "couch" to "Kanepe",
        "potted plant" to "Saksı",
        "bed" to "Yatak",
        "dining table" to "Masa",
        "toilet" to "Klozet",
        "tv" to "TV",
        "laptop" to "Laptop",
        "mouse" to "Fare",
        "remote" to "Kumanda",
        "keyboard" to "Klavye",
        "cell phone" to "Telefon",
        "microwave" to "Mikrodalga",
        "oven" to "Fırın",
        "toaster" to "Tost makinesi",
        "sink" to "Lavabo",
        "refrigerator" to "Buzdolabı",
        "book" to "Kitap",
        "clock" to "Saat",
        "vase" to "Vazo",
        "scissors" to "Makas",
        "teddy bear" to "Oyuncak ayı",
        "hair drier" to "Saç kurutma",
        "toothbrush" to "Diş fırçası"
    )
}

object LabelsDe {
    val MAP = mapOf(
        "person" to "Person",
        "bicycle" to "Fahrrad",
        "car" to "Auto",
        "motorcycle" to "Motorrad",
        "airplane" to "Flugzeug",
        "bus" to "Bus",
        "train" to "Zug",
        "truck" to "LKW",
        "boat" to "Boot",
        "traffic light" to "Ampel",
        "fire hydrant" to "Hydrant",
        "stop sign" to "Stoppschild",
        "parking meter" to "Parkuhr",
        "bench" to "Bank",
        "bird" to "Vogel",
        "cat" to "Katze",
        "dog" to "Hund",
        "horse" to "Pferd",
        "sheep" to "Schaf",
        "cow" to "Kuh",
        "elephant" to "Elefant",
        "bear" to "Bär",
        "zebra" to "Zebra",
        "giraffe" to "Giraffe",
        "backpack" to "Rucksack",
        "umbrella" to "Regenschirm",
        "handbag" to "Handtasche",
        "tie" to "Krawatte",
        "suitcase" to "Koffer",
        "frisbee" to "Frisbee",
        "skis" to "Ski",
        "snowboard" to "Snowboard",
        "sports ball" to "Ball",
        "kite" to "Drachen",
        "baseball bat" to "Baseballschläger",
        "baseball glove" to "Baseballhandschuh",
        "skateboard" to "Skateboard",
        "surfboard" to "Surfbrett",
        "tennis racket" to "Tennisschläger",
        "bottle" to "Flasche",
        "wine glass" to "Weinglas",
        "cup" to "Tasse",
        "fork" to "Gabel",
        "knife" to "Messer",
        "spoon" to "Löffel",
        "bowl" to "Schüssel",
        "banana" to "Banane",
        "apple" to "Apfel",
        "sandwich" to "Sandwich",
        "orange" to "Orange",
        "broccoli" to "Brokkoli",
        "carrot" to "Karotte",
        "hot dog" to "Hotdog",
        "pizza" to "Pizza",
        "donut" to "Donut",
        "cake" to "Kuchen",
        "chair" to "Stuhl",
        "couch" to "Couch",
        "potted plant" to "Topfpflanze",
        "bed" to "Bett",
        "dining table" to "Esstisch",
        "toilet" to "Toilette",
        "tv" to "Fernseher",
        "laptop" to "Laptop",
        "mouse" to "Maus",
        "remote" to "Fernbedienung",
        "keyboard" to "Tastatur",
        "cell phone" to "Handy",
        "microwave" to "Mikrowelle",
        "oven" to "Ofen",
        "toaster" to "Toaster",
        "sink" to "Spüle",
        "refrigerator" to "Kühlschrank",
        "book" to "Buch",
        "clock" to "Uhr",
        "vase" to "Vase",
        "scissors" to "Schere",
        "teddy bear" to "Teddybär",
        "hair drier" to "Haartrockner",
        "toothbrush" to "Zahnbürste"
    )
}

object LabelsFr {
    val MAP = mapOf(
        "person" to "personne",
        "bicycle" to "vélo",
        "car" to "voiture",
        "motorcycle" to "moto",
        "airplane" to "avion",
        "bus" to "bus",
        "train" to "train",
        "truck" to "camion",
        "boat" to "bateau",
        "traffic light" to "feu tricolore",
        "fire hydrant" to "bouche d\'incendie",
        "stop sign" to "stop",
        "parking meter" to "horodateur",
        "bench" to "banc",
        "bird" to "oiseau",
        "cat" to "chat",
        "dog" to "chien",
        "horse" to "cheval",
        "sheep" to "mouton",
        "cow" to "vache",
        "elephant" to "éléphant",
        "bear" to "ours",
        "zebra" to "zèbre",
        "giraffe" to "girafe",
        "backpack" to "sac à dos",
        "umbrella" to "parapluie",
        "handbag" to "sac à main",
        "tie" to "cravate",
        "suitcase" to "valise",
        "frisbee" to "frisbee",
        "skis" to "skis",
        "snowboard" to "snowboard",
        "sports ball" to "ballon",
        "kite" to "cerf-volant",
        "baseball bat" to "batte de baseball",
        "baseball glove" to "gant de baseball",
        "skateboard" to "skateboard",
        "surfboard" to "planche de surf",
        "tennis racket" to "raquette de tennis",
        "bottle" to "bouteille",
        "wine glass" to "verre de vin",
        "cup" to "tasse",
        "fork" to "fourchette",
        "knife" to "couteau",
        "spoon" to "cuillère",
        "bowl" to "bol",
        "banana" to "banane",
        "apple" to "pomme",
        "sandwich" to "sandwich",
        "orange" to "orange",
        "broccoli" to "brocoli",
        "carrot" to "carotte",
        "hot dog" to "hot-dog",
        "pizza" to "pizza",
        "donut" to "donut",
        "cake" to "gâteau",
        "chair" to "chaise",
        "couch" to "canapé",
        "potted plant" to "plante en pot",
        "bed" to "lit",
        "dining table" to "table à manger",
        "toilet" to "toilettes",
        "tv" to "télé",
        "laptop" to "portable",
        "mouse" to "souris",
        "remote" to "télécommande",
        "keyboard" to "clavier",
        "cell phone" to "téléphone",
        "microwave" to "micro-ondes",
        "oven" to "four",
        "toaster" to "grille-pain",
        "sink" to "évier",
        "refrigerator" to "réfrigérateur",
        "book" to "livre",
        "clock" to "horloge",
        "vase" to "vase",
        "scissors" to "ciseaux",
        "teddy bear" to "ours en peluche",
        "hair drier" to "sèche-cheveux",
        "toothbrush" to "brosse à dents"
    )
}

object LabelsEs {
    val MAP = mapOf(
        "person" to "persona",
        "bicycle" to "bicicleta",
        "car" to "coche",
        "motorcycle" to "moto",
        "airplane" to "avión",
        "bus" to "autobús",
        "train" to "tren",
        "truck" to "camión",
        "boat" to "barco",
        "traffic light" to "semáforo",
        "fire hydrant" to "hidrante",
        "stop sign" to "señal de stop",
        "parking meter" to "parquímetro",
        "bench" to "banco",
        "bird" to "pájaro",
        "cat" to "gato",
        "dog" to "perro",
        "horse" to "caballo",
        "sheep" to "oveja",
        "cow" to "vaca",
        "elephant" to "elefante",
        "bear" to "oso",
        "zebra" to "cebra",
        "giraffe" to "jirafa",
        "backpack" to "mochila",
        "umbrella" to "paraguas",
        "handbag" to "bolso",
        "tie" to "corbata",
        "suitcase" to "maleta",
        "frisbee" to "frisbi",
        "skis" to "esquís",
        "snowboard" to "snowboard",
        "sports ball" to "pelota",
        "kite" to "cometa",
        "baseball bat" to "bate de béisbol",
        "baseball glove" to "guante de béisbol",
        "skateboard" to "patineta",
        "surfboard" to "tabla de surf",
        "tennis racket" to "raqueta de tenis",
        "bottle" to "botella",
        "wine glass" to "copa de vino",
        "cup" to "taza",
        "fork" to "tenedor",
        "knife" to "cuchillo",
        "spoon" to "cuchara",
        "bowl" to "tazón",
        "banana" to "plátano",
        "apple" to "manzana",
        "sandwich" to "sándwich",
        "orange" to "naranja",
        "broccoli" to "brócoli",
        "carrot" to "zanahoria",
        "hot dog" to "perrito caliente",
        "pizza" to "pizza",
        "donut" to "dona",
        "cake" to "pastel",
        "chair" to "silla",
        "couch" to "sofá",
        "potted plant" to "planta en maceta",
        "bed" to "cama",
        "dining table" to "mesa de comedor",
        "toilet" to "inodoro",
        "tv" to "televisor",
        "laptop" to "portátil",
        "mouse" to "ratón",
        "remote" to "control remoto",
        "keyboard" to "teclado",
        "cell phone" to "celular",
        "microwave" to "microondas",
        "oven" to "horno",
        "toaster" to "tostadora",
        "sink" to "fregadero",
        "refrigerator" to "refrigerador",
        "book" to "libro",
        "clock" to "reloj",
        "vase" to "florero",
        "scissors" to "tijeras",
        "teddy bear" to "oso de peluche",
        "hair drier" to "secador de pelo",
        "toothbrush" to "cepillo de dientes"
    )
}

object LabelsIt {
    val MAP = mapOf(
        "person" to "persona",
        "bicycle" to "bicicletta",
        "car" to "auto",
        "motorcycle" to "moto",
        "airplane" to "aereo",
        "bus" to "autobus",
        "train" to "treno",
        "truck" to "camion",
        "boat" to "barca",
        "traffic light" to "semaforo",
        "fire hydrant" to "idrante",
        "stop sign" to "stop",
        "parking meter" to "parchimetro",
        "bench" to "panchina",
        "bird" to "uccello",
        "cat" to "gatto",
        "dog" to "cane",
        "horse" to "cavallo",
        "sheep" to "pecora",
        "cow" to "mucca",
        "elephant" to "elefante",
        "bear" to "orso",
        "zebra" to "zebra",
        "giraffe" to "giraffa",
        "backpack" to "zaino",
        "umbrella" to "ombrello",
        "handbag" to "borsa",
        "tie" to "cravatta",
        "suitcase" to "valigia",
        "frisbee" to "frisbee",
        "skis" to "sci",
        "snowboard" to "snowboard",
        "sports ball" to "palla",
        "kite" to "aquilone",
        "baseball bat" to "mazza da baseball",
        "baseball glove" to "guanto da baseball",
        "skateboard" to "skateboard",
        "surfboard" to "tavola da surf",
        "tennis racket" to "racchetta da tennis",
        "bottle" to "bottiglia",
        "wine glass" to "calice",
        "cup" to "tazza",
        "fork" to "forchetta",
        "knife" to "coltello",
        "spoon" to "cucchiaio",
        "bowl" to "ciotola",
        "banana" to "banana",
        "apple" to "mela",
        "sandwich" to "panino",
        "orange" to "arancia",
        "broccoli" to "broccoli",
        "carrot" to "carota",
        "hot dog" to "hot dog",
        "pizza" to "pizza",
        "donut" to "ciambella",
        "cake" to "torta",
        "chair" to "sedia",
        "couch" to "divano",
        "potted plant" to "pianta in vaso",
        "bed" to "letto",
        "dining table" to "tavolo da pranzo",
        "toilet" to "water",
        "tv" to "tv",
        "laptop" to "portatile",
        "mouse" to "mouse",
        "remote" to "telecomando",
        "keyboard" to "tastiera",
        "cell phone" to "cellulare",
        "microwave" to "microonde",
        "oven" to "forno",
        "toaster" to "tostapane",
        "sink" to "lavello",
        "refrigerator" to "frigorifero",
        "book" to "libro",
        "clock" to "orologio",
        "vase" to "vaso",
        "scissors" to "forbici",
        "teddy bear" to "orsacchiotto",
        "hair drier" to "asciugacapelli",
        "toothbrush" to "spazzolino"
    )
}

object LabelsPt {
    val MAP = mapOf(
        "person" to "pessoa",
        "bicycle" to "bicicleta",
        "car" to "carro",
        "motorcycle" to "moto",
        "airplane" to "avião",
        "bus" to "ônibus",
        "train" to "trem",
        "truck" to "caminhão",
        "boat" to "barco",
        "traffic light" to "semáforo",
        "fire hydrant" to "hidrante",
        "stop sign" to "placa pare",
        "parking meter" to "parquímetro",
        "bench" to "banco",
        "bird" to "pássaro",
        "cat" to "gato",
        "dog" to "cachorro",
        "horse" to "cavalo",
        "sheep" to "ovelha",
        "cow" to "vaca",
        "elephant" to "elefante",
        "bear" to "urso",
        "zebra" to "zebra",
        "giraffe" to "girafa",
        "backpack" to "mochila",
        "umbrella" to "guarda-chuva",
        "handbag" to "bolsa",
        "tie" to "gravata",
        "suitcase" to "mala",
        "frisbee" to "frisbee",
        "skis" to "esquis",
        "snowboard" to "snowboard",
        "sports ball" to "bola",
        "kite" to "pipa",
        "baseball bat" to "taco de beisebol",
        "baseball glove" to "luva de beisebol",
        "skateboard" to "skate",
        "surfboard" to "prancha de surfe",
        "tennis racket" to "raquete de tênis",
        "bottle" to "garrafa",
        "wine glass" to "taça de vinho",
        "cup" to "copo",
        "fork" to "garfo",
        "knife" to "faca",
        "spoon" to "colher",
        "bowl" to "tigela",
        "banana" to "banana",
        "apple" to "maçã",
        "sandwich" to "sanduíche",
        "orange" to "laranja",
        "broccoli" to "brócolis",
        "carrot" to "cenoura",
        "hot dog" to "cachorro-quente",
        "pizza" to "pizza",
        "donut" to "donut",
        "cake" to "bolo",
        "chair" to "cadeira",
        "couch" to "sofá",
        "potted plant" to "planta em vaso",
        "bed" to "cama",
        "dining table" to "mesa de jantar",
        "toilet" to "vaso sanitário",
        "tv" to "tv",
        "laptop" to "laptop",
        "mouse" to "mouse",
        "remote" to "controle remoto",
        "keyboard" to "teclado",
        "cell phone" to "celular",
        "microwave" to "micro-ondas",
        "oven" to "forno",
        "toaster" to "torradeira",
        "sink" to "pia",
        "refrigerator" to "geladeira",
        "book" to "livro",
        "clock" to "relógio",
        "vase" to "vaso",
        "scissors" to "tesoura",
        "teddy bear" to "ursinho",
        "hair drier" to "secador de cabelo",
        "toothbrush" to "escova de dentes"
    )
}

object LabelsRu {
    val MAP = mapOf(
        "person" to "человек",
        "bicycle" to "велосипед",
        "car" to "машина",
        "motorcycle" to "мотоцикл",
        "airplane" to "самолёт",
        "bus" to "автобус",
        "train" to "поезд",
        "truck" to "грузовик",
        "boat" to "лодка",
        "traffic light" to "светофор",
        "fire hydrant" to "гидрант",
        "stop sign" to "знак стоп",
        "parking meter" to "паркомат",
        "bench" to "скамейка",
        "bird" to "птица",
        "cat" to "кошка",
        "dog" to "собака",
        "horse" to "лошадь",
        "sheep" to "овца",
        "cow" to "корова",
        "elephant" to "слон",
        "bear" to "медведь",
        "zebra" to "зебра",
        "giraffe" to "жираф",
        "backpack" to "рюкзак",
        "umbrella" to "зонт",
        "handbag" to "сумка",
        "tie" to "галстук",
        "suitcase" to "чемодан",
        "frisbee" to "фрисби",
        "skis" to "лыжи",
        "snowboard" to "сноуборд",
        "sports ball" to "мяч",
        "kite" to "воздушный змей",
        "baseball bat" to "бита",
        "baseball glove" to "перчатка",
        "skateboard" to "скейтборд",
        "surfboard" to "сёрф",
        "tennis racket" to "теннисная ракетка",
        "bottle" to "бутылка",
        "wine glass" to "бокал",
        "cup" to "чашка",
        "fork" to "вилка",
        "knife" to "нож",
        "spoon" to "ложка",
        "bowl" to "миска",
        "banana" to "банан",
        "apple" to "яблоко",
        "sandwich" to "сэндвич",
        "orange" to "апельсин",
        "broccoli" to "брокколи",
        "carrot" to "морковь",
        "hot dog" to "хот-дог",
        "pizza" to "пицца",
        "donut" to "пончик",
        "cake" to "торт",
        "chair" to "стул",
        "couch" to "диван",
        "potted plant" to "цветок",
        "bed" to "кровать",
        "dining table" to "стол",
        "toilet" to "туалет",
        "tv" to "телевизор",
        "laptop" to "ноутбук",
        "mouse" to "мышь",
        "remote" to "пульт",
        "keyboard" to "клавиатура",
        "cell phone" to "телефон",
        "microwave" to "микроволновка",
        "oven" to "печь",
        "toaster" to "тостер",
        "sink" to "раковина",
        "refrigerator" to "холодильник",
        "book" to "книга",
        "clock" to "часы",
        "vase" to "ваза",
        "scissors" to "ножницы",
        "teddy bear" to "мишка",
        "hair drier" to "фен",
        "toothbrush" to "щётка"
    )
}

object LabelsUk {
    val MAP = mapOf(
        "person" to "людина",
        "bicycle" to "велосипед",
        "car" to "машина",
        "motorcycle" to "мотоцикл",
        "airplane" to "літак",
        "bus" to "автобус",
        "train" to "поїзд",
        "truck" to "вантажівка",
        "boat" to "човен",
        "traffic light" to "світлофор",
        "fire hydrant" to "гідрант",
        "stop sign" to "знак стоп",
        "parking meter" to "паркомат",
        "bench" to "лавка",
        "bird" to "птах",
        "cat" to "кіт",
        "dog" to "собака",
        "horse" to "кінь",
        "sheep" to "вівця",
        "cow" to "корова",
        "elephant" to "слон",
        "bear" to "ведмідь",
        "zebra" to "зебра",
        "giraffe" to "жирафа",
        "backpack" to "рюкзак",
        "umbrella" to "парасолька",
        "handbag" to "сумка",
        "tie" to "краватка",
        "suitcase" to "валіза",
        "frisbee" to "фризбі",
        "skis" to "лижі",
        "snowboard" to "сноуборд",
        "sports ball" to "м\'яч",
        "kite" to "змія",
        "baseball bat" to "біта",
        "baseball glove" to "рукавичка",
        "skateboard" to "скейтборд",
        "surfboard" to "серф",
        "tennis racket" to "тенісна ракетка",
        "bottle" to "пляшка",
        "wine glass" to "келих",
        "cup" to "чашка",
        "fork" to "виделка",
        "knife" to "ніж",
        "spoon" to "ложка",
        "bowl" to "миска",
        "banana" to "банан",
        "apple" to "яблуко",
        "sandwich" to "сендвіч",
        "orange" to "апельсин",
        "broccoli" to "броколі",
        "carrot" to "морква",
        "hot dog" to "хот-дог",
        "pizza" to "піца",
        "donut" to "пончик",
        "cake" to "торт",
        "chair" to "стілець",
        "couch" to "диван",
        "potted plant" to "вазон",
        "bed" to "ліжко",
        "dining table" to "стіл",
        "toilet" to "туалет",
        "tv" to "телевізор",
        "laptop" to "ноутбук",
        "mouse" to "миша",
        "remote" to "пульт",
        "keyboard" to "клавіатура",
        "cell phone" to "телефон",
        "microwave" to "мікрохвильовка",
        "oven" to "піч",
        "toaster" to "тостер",
        "sink" to "раковина",
        "refrigerator" to "холодильник",
        "book" to "книга",
        "clock" to "годинник",
        "vase" to "ваза",
        "scissors" to "ножиці",
        "teddy bear" to "ведмедик",
        "hair drier" to "фен",
        "toothbrush" to "щітка"
    )
}

object LabelsAr {
    val MAP = mapOf(
        "person" to "شخص",
        "bicycle" to "دراجة",
        "car" to "سيارة",
        "motorcycle" to "دراجة نارية",
        "airplane" to "طائرة",
        "bus" to "حافلة",
        "train" to "قطار",
        "truck" to "شاحنة",
        "boat" to "قارب",
        "traffic light" to "إشارة مرور",
        "fire hydrant" to "صنبور إطفاء",
        "stop sign" to "علامة قف",
        "parking meter" to "عداد وقوف",
        "bench" to "مقعد",
        "bird" to "طائر",
        "cat" to "قطة",
        "dog" to "كلب",
        "horse" to "حصان",
        "sheep" to "خروف",
        "cow" to "بقرة",
        "elephant" to "فيل",
        "bear" to "دب",
        "zebra" to "حمار وحشي",
        "giraffe" to "زرافة",
        "backpack" to "حقيبة ظهر",
        "umbrella" to "مظلة",
        "handbag" to "حقيبة يد",
        "tie" to "ربطة عنق",
        "suitcase" to "حقيبة سفر",
        "frisbee" to "فريسبي",
        "skis" to "زلاجات",
        "snowboard" to "لوح تزلج",
        "sports ball" to "كرة",
        "kite" to "طائرة ورقية",
        "baseball bat" to "مضرب بيسبول",
        "baseball glove" to "قفاز بيسبول",
        "skateboard" to "سكيت بورد",
        "surfboard" to "لوح ركوب الأمواج",
        "tennis racket" to "مضرب تنس",
        "bottle" to "زجاجة",
        "wine glass" to "كأس نبيذ",
        "cup" to "كوب",
        "fork" to "شوكة",
        "knife" to "سكين",
        "spoon" to "ملعقة",
        "bowl" to "وعاء",
        "banana" to "موز",
        "apple" to "تفاح",
        "sandwich" to "ساندويتش",
        "orange" to "برتقال",
        "broccoli" to "بروكلي",
        "carrot" to "جزر",
        "hot dog" to "هوت دوغ",
        "pizza" to "بيتزا",
        "donut" to "دونات",
        "cake" to "كعكة",
        "chair" to "كرسي",
        "couch" to "أريكة",
        "potted plant" to "نبتة",
        "bed" to "سرير",
        "dining table" to "طاولة طعام",
        "toilet" to "مرحاض",
        "tv" to "تلفاز",
        "laptop" to "حاسوب محمول",
        "mouse" to "فأرة",
        "remote" to "جهاز تحكم",
        "keyboard" to "لوحة مفاتيح",
        "cell phone" to "هاتف",
        "microwave" to "ميكروويف",
        "oven" to "فرن",
        "toaster" to "محمصة",
        "sink" to "حوض",
        "refrigerator" to "ثلاجة",
        "book" to "كتاب",
        "clock" to "ساعة",
        "vase" to "مزهرية",
        "scissors" to "مقص",
        "teddy bear" to "دب لعبة",
        "hair drier" to "مجفف شعر",
        "toothbrush" to "فرشاة أسنان"
    )
}

object LabelsFa {
    val MAP = mapOf(
        "person" to "آدم",
        "bicycle" to "دوچرخه",
        "car" to "ماشین",
        "motorcycle" to "موتورسیکلت",
        "airplane" to "هواپیما",
        "bus" to "اتوبوس",
        "train" to "قطار",
        "truck" to "کامیون",
        "boat" to "قایق",
        "traffic light" to "چراغ راهنمایی",
        "fire hydrant" to "شیر آتش‌نشانی",
        "stop sign" to "تابلوی ایست",
        "parking meter" to "پارکومتر",
        "bench" to "نیمکت",
        "bird" to "پرنده",
        "cat" to "گربه",
        "dog" to "سگ",
        "horse" to "اسب",
        "sheep" to "گوسفند",
        "cow" to "گاو",
        "elephant" to "فیل",
        "bear" to "خرس",
        "zebra" to "گورخر",
        "giraffe" to "زرافه",
        "backpack" to "کوله‌پشتی",
        "umbrella" to "چتر",
        "handbag" to "کیف دستی",
        "tie" to "کراوات",
        "suitcase" to "چمدان",
        "frisbee" to "فریزبی",
        "skis" to "اسکی",
        "snowboard" to "اسنوبرد",
        "sports ball" to "توپ",
        "kite" to "بادبادک",
        "baseball bat" to "چوب بیسبال",
        "baseball glove" to "دستکش بیسبال",
        "skateboard" to "اسکیت‌برد",
        "surfboard" to "تخته موج‌سواری",
        "tennis racket" to "راکت تنیس",
        "bottle" to "بطری",
        "wine glass" to "لیوان شراب",
        "cup" to "فنجان",
        "fork" to "چنگال",
        "knife" to "چاقو",
        "spoon" to "قاشق",
        "bowl" to "کاسه",
        "banana" to "موز",
        "apple" to "سیب",
        "sandwich" to "ساندویچ",
        "orange" to "پرتقال",
        "broccoli" to "بروکلی",
        "carrot" to "هویج",
        "hot dog" to "هات‌داگ",
        "pizza" to "پیتزا",
        "donut" to "دونات",
        "cake" to "کیک",
        "chair" to "صندلی",
        "couch" to "مبل",
        "potted plant" to "گیاه گلدانی",
        "bed" to "تخت",
        "dining table" to "میز غذاخوری",
        "toilet" to "توالت",
        "tv" to "تلویزیون",
        "laptop" to "لپ‌تاپ",
        "mouse" to "موس",
        "remote" to "کنترل",
        "keyboard" to "صفحه‌کلید",
        "cell phone" to "تلفن",
        "microwave" to "مایکروویو",
        "oven" to "فر",
        "toaster" to "توستر",
        "sink" to "سینک",
        "refrigerator" to "یخچال",
        "book" to "کتاب",
        "clock" to "ساعت",
        "vase" to "گلدان",
        "scissors" to "قیچی",
        "teddy bear" to "خرس عروسکی",
        "hair drier" to "سشوار",
        "toothbrush" to "مسواک"
    )
}
