package com.example.speedcam

object LabelsZhCN {
    val MAP = mapOf(
        "person" to "人",
        "bicycle" to "自行车",
        "car" to "汽车",
        "motorcycle" to "摩托车",
        "airplane" to "飞机",
        "bus" to "公共汽车",
        "train" to "火车",
        "truck" to "卡车",
        "boat" to "船",
        "traffic light" to "红绿灯",
        "fire hydrant" to "消防栓",
        "stop sign" to "停车标志",
        "parking meter" to "咪表",
        "bench" to "长椅",
        "bird" to "鸟",
        "cat" to "猫",
        "dog" to "狗",
        "horse" to "马",
        "sheep" to "绵羊",
        "cow" to "奶牛",
        "elephant" to "大象",
        "bear" to "熊",
        "zebra" to "斑马",
        "giraffe" to "长颈鹿",
        "backpack" to "背包",
        "umbrella" to "雨伞",
        "handbag" to "手提包",
        "tie" to "领带",
        "suitcase" to "手提箱",
        "frisbee" to "飞盘",
        "skis" to "滑雪板",
        "snowboard" to "单板滑雪",
        "sports ball" to "运动球",
        "kite" to "风筝",
        "baseball bat" to "棒球棒",
        "baseball glove" to "棒球手套",
        "skateboard" to "滑板",
        "surfboard" to "冲浪板",
        "tennis racket" to "网球拍",
        "bottle" to "瓶子",
        "wine glass" to "酒杯",
        "cup" to "杯子",
        "fork" to "叉子",
        "knife" to "刀",
        "spoon" to "勺子",
        "bowl" to "碗",
        "banana" to "香蕉",
        "apple" to "苹果",
        "sandwich" to "三明治",
        "orange" to "橙子",
        "broccoli" to "西兰花",
        "carrot" to "胡萝卜",
        "hot dog" to "热狗",
        "pizza" to "披萨",
        "donut" to "甜甜圈",
        "cake" to "蛋糕",
        "chair" to "椅子",
        "couch" to "沙发",
        "potted plant" to "盆栽",
        "bed" to "床",
        "dining table" to "餐桌",
        "toilet" to "马桶",
        "tv" to "电视",
        "laptop" to "笔记本电脑",
        "mouse" to "鼠标",
        "remote" to "遥控器",
        "keyboard" to "键盘",
        "cell phone" to "手机",
        "microwave" to "微波炉",
        "oven" to "烤箱",
        "toaster" to "烤面包机",
        "sink" to "水槽",
        "refrigerator" to "冰箱",
        "book" to "书",
        "clock" to "时钟",
        "vase" to "花瓶",
        "scissors" to "剪刀",
        "teddy bear" to "泰迪熊",
        "hair drier" to "吹风机",
        "toothbrush" to "牙刷"
    )
}

object LabelsZhTW {
    val MAP = mapOf(
        "person" to "人",
        "bicycle" to "腳踏車",
        "car" to "汽車",
        "motorcycle" to "機車",
        "airplane" to "飛機",
        "bus" to "公車",
        "train" to "火車",
        "truck" to "卡車",
        "boat" to "船",
        "traffic light" to "紅綠燈",
        "fire hydrant" to "消防栓",
        "stop sign" to "停車標誌",
        "parking meter" to "停車咪錶",
        "bench" to "長椅",
        "bird" to "鳥",
        "cat" to "貓",
        "dog" to "狗",
        "horse" to "馬",
        "sheep" to "綿羊",
        "cow" to "乳牛",
        "elephant" to "大象",
        "bear" to "熊",
        "zebra" to "斑馬",
        "giraffe" to "長頸鹿",
        "backpack" to "背包",
        "umbrella" to "雨傘",
        "handbag" to "手提包",
        "tie" to "領帶",
        "suitcase" to "手提箱",
        "frisbee" to "飛盤",
        "skis" to "滑雪板",
        "snowboard" to "單板滑雪",
        "sports ball" to "運動球",
        "kite" to "風箏",
        "baseball bat" to "棒球棒",
        "baseball glove" to "棒球手套",
        "skateboard" to "滑板",
        "surfboard" to "衝浪板",
        "tennis racket" to "網球拍",
        "bottle" to "瓶子",
        "wine glass" to "酒杯",
        "cup" to "杯子",
        "fork" to "叉子",
        "knife" to "刀",
        "spoon" to "湯匙",
        "bowl" to "碗",
        "banana" to "香蕉",
        "apple" to "蘋果",
        "sandwich" to "三明治",
        "orange" to "柳橙",
        "broccoli" to "花椰菜",
        "carrot" to "胡蘿蔔",
        "hot dog" to "熱狗",
        "pizza" to "披薩",
        "donut" to "甜甜圈",
        "cake" to "蛋糕",
        "chair" to "椅子",
        "couch" to "沙發",
        "potted plant" to "盆栽",
        "bed" to "床",
        "dining table" to "餐桌",
        "toilet" to "馬桶",
        "tv" to "電視",
        "laptop" to "筆記型電腦",
        "mouse" to "滑鼠",
        "remote" to "遙控器",
        "keyboard" to "鍵盤",
        "cell phone" to "手機",
        "microwave" to "微波爐",
        "oven" to "烤箱",
        "toaster" to "烤麵包機",
        "sink" to "水槽",
        "refrigerator" to "冰箱",
        "book" to "書",
        "clock" to "時鐘",
        "vase" to "花瓶",
        "scissors" to "剪刀",
        "teddy bear" to "泰迪熊",
        "hair drier" to "吹風機",
        "toothbrush" to "牙刷"
    )
}

object LabelsJa {
    val MAP = mapOf(
        "person" to "人",
        "bicycle" to "自転車",
        "car" to "車",
        "motorcycle" to "バイク",
        "airplane" to "飛行機",
        "bus" to "バス",
        "train" to "電車",
        "truck" to "トラック",
        "boat" to "ボート",
        "traffic light" to "信号機",
        "fire hydrant" to "消火栓",
        "stop sign" to "停止標識",
        "parking meter" to "パーキングメーター",
        "bench" to "ベンチ",
        "bird" to "鳥",
        "cat" to "猫",
        "dog" to "犬",
        "horse" to "馬",
        "sheep" to "羊",
        "cow" to "牛",
        "elephant" to "象",
        "bear" to "熊",
        "zebra" to "シマウマ",
        "giraffe" to "キリン",
        "backpack" to "リュック",
        "umbrella" to "傘",
        "handbag" to "ハンドバッグ",
        "tie" to "ネクタイ",
        "suitcase" to "スーツケース",
        "frisbee" to "フリスビー",
        "skis" to "スキー",
        "snowboard" to "スノーボード",
        "sports ball" to "ボール",
        "kite" to "凧",
        "baseball bat" to "バット",
        "baseball glove" to "グローブ",
        "skateboard" to "スケボー",
        "surfboard" to "サーフボード",
        "tennis racket" to "ラケット",
        "bottle" to "ボトル",
        "wine glass" to "ワイングラス",
        "cup" to "カップ",
        "fork" to "フォーク",
        "knife" to "ナイフ",
        "spoon" to "スプーン",
        "bowl" to "ボウル",
        "banana" to "バナナ",
        "apple" to "りんご",
        "sandwich" to "サンドイッチ",
        "orange" to "オレンジ",
        "broccoli" to "ブロッコリー",
        "carrot" to "にんじん",
        "hot dog" to "ホットドッグ",
        "pizza" to "ピザ",
        "donut" to "ドーナツ",
        "cake" to "ケーキ",
        "chair" to "椅子",
        "couch" to "ソファ",
        "potted plant" to "観葉植物",
        "bed" to "ベッド",
        "dining table" to "食卓",
        "toilet" to "トイレ",
        "tv" to "テレビ",
        "laptop" to "ノートPC",
        "mouse" to "マウス",
        "remote" to "リモコン",
        "keyboard" to "キーボード",
        "cell phone" to "携帯電話",
        "microwave" to "電子レンジ",
        "oven" to "オーブン",
        "toaster" to "トースター",
        "sink" to "シンク",
        "refrigerator" to "冷蔵庫",
        "book" to "本",
        "clock" to "時計",
        "vase" to "花瓶",
        "scissors" to "はさみ",
        "teddy bear" to "ぬいぐるみ",
        "hair drier" to "ドライヤー",
        "toothbrush" to "歯ブラシ"
    )
}

object LabelsKo {
    val MAP = mapOf(
        "person" to "사람",
        "bicycle" to "자전거",
        "car" to "자동차",
        "motorcycle" to "오토바이",
        "airplane" to "비행기",
        "bus" to "버스",
        "train" to "기차",
        "truck" to "트럭",
        "boat" to "보트",
        "traffic light" to "신호등",
        "fire hydrant" to "소화전",
        "stop sign" to "정지 표지",
        "parking meter" to "주차 미터기",
        "bench" to "벤치",
        "bird" to "새",
        "cat" to "고양이",
        "dog" to "개",
        "horse" to "말",
        "sheep" to "양",
        "cow" to "소",
        "elephant" to "코끼리",
        "bear" to "곰",
        "zebra" to "얼룩말",
        "giraffe" to "기린",
        "backpack" to "배낭",
        "umbrella" to "우산",
        "handbag" to "핸드백",
        "tie" to "넥타이",
        "suitcase" to "여행가방",
        "frisbee" to "프리스비",
        "skis" to "스키",
        "snowboard" to "스노보드",
        "sports ball" to "공",
        "kite" to "연",
        "baseball bat" to "야구 배트",
        "baseball glove" to "야구 글러브",
        "skateboard" to "스케이트보드",
        "surfboard" to "서핑보드",
        "tennis racket" to "테니스 라켓",
        "bottle" to "병",
        "wine glass" to "와인잔",
        "cup" to "컵",
        "fork" to "포크",
        "knife" to "나이프",
        "spoon" to "숟가락",
        "bowl" to "그릇",
        "banana" to "바나나",
        "apple" to "사과",
        "sandwich" to "샌드위치",
        "orange" to "오렌지",
        "broccoli" to "브로콜리",
        "carrot" to "당근",
        "hot dog" to "핫도그",
        "pizza" to "피자",
        "donut" to "도넛",
        "cake" to "케이크",
        "chair" to "의자",
        "couch" to "소파",
        "potted plant" to "화분",
        "bed" to "침대",
        "dining table" to "식탁",
        "toilet" to "화장실",
        "tv" to "TV",
        "laptop" to "노트북",
        "mouse" to "마우스",
        "remote" to "리모컨",
        "keyboard" to "키보드",
        "cell phone" to "휴대전화",
        "microwave" to "전자레인지",
        "oven" to "오븐",
        "toaster" to "토스터",
        "sink" to "싱크대",
        "refrigerator" to "냉장고",
        "book" to "책",
        "clock" to "시계",
        "vase" to "꽃병",
        "scissors" to "가위",
        "teddy bear" to "테디베어",
        "hair drier" to "드라이기",
        "toothbrush" to "칫솔"
    )
}

object LabelsHi {
    val MAP = mapOf(
        "person" to "व्यक्ति",
        "bicycle" to "साइकिल",
        "car" to "कार",
        "motorcycle" to "मोटरसाइकिल",
        "airplane" to "हवाई जहाज",
        "bus" to "बस",
        "train" to "ट्रेन",
        "truck" to "ट्रक",
        "boat" to "नाव",
        "traffic light" to "ट्रैफिक लाइट",
        "fire hydrant" to "फायर हाइड्रेंट",
        "stop sign" to "स्टॉप साइन",
        "parking meter" to "पार्किंग मीटर",
        "bench" to "बेंच",
        "bird" to "पक्षी",
        "cat" to "बिल्ली",
        "dog" to "कुत्ता",
        "horse" to "घोड़ा",
        "sheep" to "भेड़",
        "cow" to "गाय",
        "elephant" to "हाथी",
        "bear" to "भालू",
        "zebra" to "ज़ेबरा",
        "giraffe" to "जिराफ",
        "backpack" to "बैगपैक",
        "umbrella" to "छाता",
        "handbag" to "हैंडबैग",
        "tie" to "टाई",
        "suitcase" to "सूटकेस",
        "frisbee" to "फ्रिसबी",
        "skis" to "स्की",
        "snowboard" to "स्नोबोर्ड",
        "sports ball" to "गेंद",
        "kite" to "पतंग",
        "baseball bat" to "बेसबॉल बैट",
        "baseball glove" to "बेसबॉल दस्ताना",
        "skateboard" to "स्केटबोर्ड",
        "surfboard" to "सर्फबोर्ड",
        "tennis racket" to "टेनिस रैकेट",
        "bottle" to "बोतल",
        "wine glass" to "वाइन गिलास",
        "cup" to "कप",
        "fork" to "कांटा",
        "knife" to "चाकू",
        "spoon" to "चम्मच",
        "bowl" to "कटोरा",
        "banana" to "केला",
        "apple" to "सेब",
        "sandwich" to "सैंडविच",
        "orange" to "संतरा",
        "broccoli" to "ब्रोकली",
        "carrot" to "गाजर",
        "hot dog" to "हॉट डॉग",
        "pizza" to "पिज्जा",
        "donut" to "डोनट",
        "cake" to "केक",
        "chair" to "कुर्सी",
        "couch" to "सोफा",
        "potted plant" to "गमले का पौधा",
        "bed" to "बिस्तर",
        "dining table" to "खाने की मेज",
        "toilet" to "शौचालय",
        "tv" to "टीवी",
        "laptop" to "लैपटॉप",
        "mouse" to "माउस",
        "remote" to "रिमोट",
        "keyboard" to "कीबोर्ड",
        "cell phone" to "मोबाइल",
        "microwave" to "माइक्रोवेव",
        "oven" to "ओवन",
        "toaster" to "टोस्टर",
        "sink" to "सिंक",
        "refrigerator" to "फ्रिज",
        "book" to "किताब",
        "clock" to "घड़ी",
        "vase" to "फूलदान",
        "scissors" to "कैंची",
        "teddy bear" to "टेडी बियर",
        "hair drier" to "हेयर ड्रायर",
        "toothbrush" to "टूथब्रश"
    )
}

object LabelsId {
    val MAP = mapOf(
        "person" to "orang",
        "bicycle" to "sepeda",
        "car" to "mobil",
        "motorcycle" to "motor",
        "airplane" to "pesawat",
        "bus" to "bus",
        "train" to "kereta",
        "truck" to "truk",
        "boat" to "perahu",
        "traffic light" to "lampu lalu lintas",
        "fire hydrant" to "hidran",
        "stop sign" to "rambu berhenti",
        "parking meter" to "meter parkir",
        "bench" to "bangku",
        "bird" to "burung",
        "cat" to "kucing",
        "dog" to "anjing",
        "horse" to "kuda",
        "sheep" to "domba",
        "cow" to "sapi",
        "elephant" to "gajah",
        "bear" to "beruang",
        "zebra" to "zebra",
        "giraffe" to "jerapah",
        "backpack" to "ransel",
        "umbrella" to "payung",
        "handbag" to "tas tangan",
        "tie" to "dasi",
        "suitcase" to "koper",
        "frisbee" to "frisbee",
        "skis" to "ski",
        "snowboard" to "snowboard",
        "sports ball" to "bola",
        "kite" to "layang-layang",
        "baseball bat" to "pemukul bisbol",
        "baseball glove" to "sarung bisbol",
        "skateboard" to "skateboard",
        "surfboard" to "papan seluncur",
        "tennis racket" to "raket tenis",
        "bottle" to "botol",
        "wine glass" to "gelas anggur",
        "cup" to "cangkir",
        "fork" to "garpu",
        "knife" to "pisau",
        "spoon" to "sendok",
        "bowl" to "mangkuk",
        "banana" to "pisang",
        "apple" to "apel",
        "sandwich" to "sandwich",
        "orange" to "jeruk",
        "broccoli" to "brokoli",
        "carrot" to "wortel",
        "hot dog" to "hot dog",
        "pizza" to "pizza",
        "donut" to "donat",
        "cake" to "kue",
        "chair" to "kursi",
        "couch" to "sofa",
        "potted plant" to "tanaman pot",
        "bed" to "tempat tidur",
        "dining table" to "meja makan",
        "toilet" to "toilet",
        "tv" to "tv",
        "laptop" to "laptop",
        "mouse" to "mouse",
        "remote" to "remote",
        "keyboard" to "keyboard",
        "cell phone" to "ponsel",
        "microwave" to "microwave",
        "oven" to "oven",
        "toaster" to "pemanggang roti",
        "sink" to "wastafel",
        "refrigerator" to "kulkas",
        "book" to "buku",
        "clock" to "jam",
        "vase" to "vas",
        "scissors" to "gunting",
        "teddy bear" to "boneka beruang",
        "hair drier" to "pengering rambut",
        "toothbrush" to "sikat gigi"
    )
}

object LabelsMs {
    val MAP = mapOf(
        "person" to "orang",
        "bicycle" to "basikal",
        "car" to "kereta",
        "motorcycle" to "motosikal",
        "airplane" to "kapal terbang",
        "bus" to "bas",
        "train" to "kereta api",
        "truck" to "lori",
        "boat" to "bot",
        "traffic light" to "lampu isyarat",
        "fire hydrant" to "pili bomba",
        "stop sign" to "papan berhenti",
        "parking meter" to "meter parkir",
        "bench" to "bangku",
        "bird" to "burung",
        "cat" to "kucing",
        "dog" to "anjing",
        "horse" to "kuda",
        "sheep" to "biri-biri",
        "cow" to "lembu",
        "elephant" to "gajah",
        "bear" to "beruang",
        "zebra" to "zebra",
        "giraffe" to "zirafah",
        "backpack" to "beg galas",
        "umbrella" to "payung",
        "handbag" to "beg tangan",
        "tie" to "tali leher",
        "suitcase" to "beg pakaian",
        "frisbee" to "frisbee",
        "skis" to "ski",
        "snowboard" to "papan salji",
        "sports ball" to "bola",
        "kite" to "layang-layang",
        "baseball bat" to "pemukul besbol",
        "baseball glove" to "sarung besbol",
        "skateboard" to "papan selaju",
        "surfboard" to "papan luncur",
        "tennis racket" to "raket tenis",
        "bottle" to "botol",
        "wine glass" to "gelas wain",
        "cup" to "cawan",
        "fork" to "garpu",
        "knife" to "pisau",
        "spoon" to "sudu",
        "bowl" to "mangkuk",
        "banana" to "pisang",
        "apple" to "epal",
        "sandwich" to "sandwic",
        "orange" to "oren",
        "broccoli" to "brokoli",
        "carrot" to "lobak merah",
        "hot dog" to "hot dog",
        "pizza" to "piza",
        "donut" to "donat",
        "cake" to "kek",
        "chair" to "kerusi",
        "couch" to "sofa",
        "potted plant" to "pokok pasu",
        "bed" to "katil",
        "dining table" to "meja makan",
        "toilet" to "tandas",
        "tv" to "tv",
        "laptop" to "komputer riba",
        "mouse" to "tetikus",
        "remote" to "alat kawalan",
        "keyboard" to "papan kekunci",
        "cell phone" to "telefon",
        "microwave" to "gelombang mikro",
        "oven" to "ketuhar",
        "toaster" to "pembakar roti",
        "sink" to "sinki",
        "refrigerator" to "peti sejuk",
        "book" to "buku",
        "clock" to "jam",
        "vase" to "pasu",
        "scissors" to "gunting",
        "teddy bear" to "anak patung beruang",
        "hair drier" to "pengering rambut",
        "toothbrush" to "berus gigi"
    )
}

object LabelsTh {
    val MAP = mapOf(
        "person" to "คน",
        "bicycle" to "จักรยาน",
        "car" to "รถยนต์",
        "motorcycle" to "มอเตอร์ไซค์",
        "airplane" to "เครื่องบิน",
        "bus" to "รถบัส",
        "train" to "รถไฟ",
        "truck" to "รถบรรทุก",
        "boat" to "เรือ",
        "traffic light" to "ไฟจราจร",
        "fire hydrant" to "หัวดับเพลิง",
        "stop sign" to "ป้ายหยุด",
        "parking meter" to "มิเตอร์จอดรถ",
        "bench" to "ม้านั่ง",
        "bird" to "นก",
        "cat" to "แมว",
        "dog" to "สุนัข",
        "horse" to "ม้า",
        "sheep" to "แกะ",
        "cow" to "วัว",
        "elephant" to "ช้าง",
        "bear" to "หมี",
        "zebra" to "ม้าลาย",
        "giraffe" to "ยีราฟ",
        "backpack" to "กระเป๋าเป้",
        "umbrella" to "ร่ม",
        "handbag" to "กระเป๋าถือ",
        "tie" to "เนคไท",
        "suitcase" to "กระเป๋าเดินทาง",
        "frisbee" to "จานร่อน",
        "skis" to "สกี",
        "snowboard" to "สโนว์บอร์ด",
        "sports ball" to "ลูกบอล",
        "kite" to "ว่าว",
        "baseball bat" to "ไม้เบสบอล",
        "baseball glove" to "ถุงมือเบสบอล",
        "skateboard" to "สเกตบอร์ด",
        "surfboard" to "กระดานโต้คลื่น",
        "tennis racket" to "ไม้เทนนิส",
        "bottle" to "ขวด",
        "wine glass" to "แก้วไวน์",
        "cup" to "ถ้วย",
        "fork" to "ส้อม",
        "knife" to "มีด",
        "spoon" to "ช้อน",
        "bowl" to "ชาม",
        "banana" to "กล้วย",
        "apple" to "แอปเปิล",
        "sandwich" to "แซนด์วิช",
        "orange" to "ส้ม",
        "broccoli" to "บรอกโคลี",
        "carrot" to "แครอท",
        "hot dog" to "ฮอตดอก",
        "pizza" to "พิซซ่า",
        "donut" to "โดนัท",
        "cake" to "เค้ก",
        "chair" to "เก้าอี้",
        "couch" to "โซฟา",
        "potted plant" to "ไม้กระถาง",
        "bed" to "เตียง",
        "dining table" to "โต๊ะอาหาร",
        "toilet" to "ห้องน้ำ",
        "tv" to "ทีวี",
        "laptop" to "แล็ปท็อป",
        "mouse" to "เมาส์",
        "remote" to "รีโมท",
        "keyboard" to "คีย์บอร์ด",
        "cell phone" to "โทรศัพท์",
        "microwave" to "ไมโครเวฟ",
        "oven" to "เตาอบ",
        "toaster" to "เครื่องปิ้งขนมปัง",
        "sink" to "อ่างล้าง",
        "refrigerator" to "ตู้เย็น",
        "book" to "หนังสือ",
        "clock" to "นาฬิกา",
        "vase" to "แจกัน",
        "scissors" to "กรรไกร",
        "teddy bear" to "ตุ๊กตาหมี",
        "hair drier" to "ไดร์เป่าผม",
        "toothbrush" to "แปรงสีฟัน"
    )
}

object LabelsVi {
    val MAP = mapOf(
        "person" to "người",
        "bicycle" to "xe đạp",
        "car" to "ô tô",
        "motorcycle" to "xe máy",
        "airplane" to "máy bay",
        "bus" to "xe buýt",
        "train" to "tàu hỏa",
        "truck" to "xe tải",
        "boat" to "thuyền",
        "traffic light" to "đèn giao thông",
        "fire hydrant" to "trụ cứu hỏa",
        "stop sign" to "biển dừng",
        "parking meter" to "đồng hồ đỗ xe",
        "bench" to "ghế dài",
        "bird" to "chim",
        "cat" to "mèo",
        "dog" to "chó",
        "horse" to "ngựa",
        "sheep" to "cừu",
        "cow" to "bò",
        "elephant" to "voi",
        "bear" to "gấu",
        "zebra" to "ngựa vằn",
        "giraffe" to "hươu cao cổ",
        "backpack" to "ba lô",
        "umbrella" to "ô",
        "handbag" to "túi xách",
        "tie" to "cà vạt",
        "suitcase" to "va li",
        "frisbee" to "đĩa bay",
        "skis" to "ván trượt tuyết",
        "snowboard" to "ván trượt",
        "sports ball" to "bóng",
        "kite" to "diều",
        "baseball bat" to "gậy bóng chày",
        "baseball glove" to "găng bóng chày",
        "skateboard" to "ván trượt",
        "surfboard" to "ván lướt sóng",
        "tennis racket" to "vợt tennis",
        "bottle" to "chai",
        "wine glass" to "ly rượu",
        "cup" to "cốc",
        "fork" to "nĩa",
        "knife" to "dao",
        "spoon" to "thìa",
        "bowl" to "bát",
        "banana" to "chuối",
        "apple" to "táo",
        "sandwich" to "sandwich",
        "orange" to "cam",
        "broccoli" to "súp lơ xanh",
        "carrot" to "cà rốt",
        "hot dog" to "hot dog",
        "pizza" to "pizza",
        "donut" to "donut",
        "cake" to "bánh",
        "chair" to "ghế",
        "couch" to "sofa",
        "potted plant" to "chậu cây",
        "bed" to "giường",
        "dining table" to "bàn ăn",
        "toilet" to "toilet",
        "tv" to "tv",
        "laptop" to "laptop",
        "mouse" to "chuột",
        "remote" to "điều khiển",
        "keyboard" to "bàn phím",
        "cell phone" to "điện thoại",
        "microwave" to "lò vi sóng",
        "oven" to "lò nướng",
        "toaster" to "máy nướng bánh",
        "sink" to "bồn rửa",
        "refrigerator" to "tủ lạnh",
        "book" to "sách",
        "clock" to "đồng hồ",
        "vase" to "lọ hoa",
        "scissors" to "kéo",
        "teddy bear" to "gấu bông",
        "hair drier" to "máy sấy tóc",
        "toothbrush" to "bàn chải"
    )
}
