package com.example.speedcam

object LabelsPl {
    val MAP = mapOf(
        "person" to "osoba",
        "bicycle" to "rower",
        "car" to "samochód",
        "motorcycle" to "motocykl",
        "airplane" to "samolot",
        "bus" to "autobus",
        "train" to "pociąg",
        "truck" to "ciężarówka",
        "boat" to "łódź",
        "traffic light" to "sygnalizacja",
        "fire hydrant" to "hydrant",
        "stop sign" to "znak stop",
        "parking meter" to "parkometr",
        "bench" to "ławka",
        "bird" to "ptak",
        "cat" to "kot",
        "dog" to "pies",
        "horse" to "koń",
        "sheep" to "owca",
        "cow" to "krowa",
        "elephant" to "słoń",
        "bear" to "niedźwiedź",
        "zebra" to "zebra",
        "giraffe" to "żyrafa",
        "backpack" to "plecak",
        "umbrella" to "parasol",
        "handbag" to "torebka",
        "tie" to "krawat",
        "suitcase" to "walizka",
        "frisbee" to "frisbee",
        "skis" to "narty",
        "snowboard" to "snowboard",
        "sports ball" to "piłka",
        "kite" to "latawiec",
        "baseball bat" to "kij bejsbolowy",
        "baseball glove" to "rękawica bejsbolowa",
        "skateboard" to "deskorolka",
        "surfboard" to "deska surfingowa",
        "tennis racket" to "rakieta tenisowa",
        "bottle" to "butelka",
        "wine glass" to "kieliszek",
        "cup" to "kubek",
        "fork" to "widelec",
        "knife" to "nóż",
        "spoon" to "łyżka",
        "bowl" to "miska",
        "banana" to "banan",
        "apple" to "jabłko",
        "sandwich" to "kanapka",
        "orange" to "pomarańcza",
        "broccoli" to "brokuł",
        "carrot" to "marchewka",
        "hot dog" to "hot dog",
        "pizza" to "pizza",
        "donut" to "donut",
        "cake" to "tort",
        "chair" to "krzesło",
        "couch" to "sofa",
        "potted plant" to "roślina doniczkowa",
        "bed" to "łóżko",
        "dining table" to "stół",
        "toilet" to "toaleta",
        "tv" to "telewizor",
        "laptop" to "laptop",
        "mouse" to "mysz",
        "remote" to "pilot",
        "keyboard" to "klawiatura",
        "cell phone" to "telefon",
        "microwave" to "mikrofalówka",
        "oven" to "piekarnik",
        "toaster" to "toster",
        "sink" to "zlew",
        "refrigerator" to "lodówka",
        "book" to "książka",
        "clock" to "zegar",
        "vase" to "wazon",
        "scissors" to "nożyczki",
        "teddy bear" to "miś",
        "hair drier" to "suszarka",
        "toothbrush" to "szczoteczka"
    )
}

object LabelsNl {
    val MAP = mapOf(
        "person" to "persoon",
        "bicycle" to "fiets",
        "car" to "auto",
        "motorcycle" to "motor",
        "airplane" to "vliegtuig",
        "bus" to "bus",
        "train" to "trein",
        "truck" to "vrachtwagen",
        "boat" to "boot",
        "traffic light" to "verkeerslicht",
        "fire hydrant" to "brandkraan",
        "stop sign" to "stopbord",
        "parking meter" to "parkeermeter",
        "bench" to "bank",
        "bird" to "vogel",
        "cat" to "kat",
        "dog" to "hond",
        "horse" to "paard",
        "sheep" to "schaap",
        "cow" to "koe",
        "elephant" to "olifant",
        "bear" to "beer",
        "zebra" to "zebra",
        "giraffe" to "giraf",
        "backpack" to "rugzak",
        "umbrella" to "paraplu",
        "handbag" to "handtas",
        "tie" to "stropdas",
        "suitcase" to "koffer",
        "frisbee" to "frisbee",
        "skis" to "ski's",
        "snowboard" to "snowboard",
        "sports ball" to "bal",
        "kite" to "vlieger",
        "baseball bat" to "honkbalknuppel",
        "baseball glove" to "honkbalhandschoen",
        "skateboard" to "skateboard",
        "surfboard" to "surfplank",
        "tennis racket" to "tennisracket",
        "bottle" to "fles",
        "wine glass" to "wijnglas",
        "cup" to "beker",
        "fork" to "vork",
        "knife" to "mes",
        "spoon" to "lepel",
        "bowl" to "kom",
        "banana" to "banaan",
        "apple" to "appel",
        "sandwich" to "sandwich",
        "orange" to "sinaasappel",
        "broccoli" to "broccoli",
        "carrot" to "wortel",
        "hot dog" to "hotdog",
        "pizza" to "pizza",
        "donut" to "donut",
        "cake" to "taart",
        "chair" to "stoel",
        "couch" to "sofa",
        "potted plant" to "potplant",
        "bed" to "bed",
        "dining table" to "eettafel",
        "toilet" to "toilet",
        "tv" to "tv",
        "laptop" to "laptop",
        "mouse" to "muis",
        "remote" to "afstandsbediening",
        "keyboard" to "toetsenbord",
        "cell phone" to "telefoon",
        "microwave" to "magnetron",
        "oven" to "oven",
        "toaster" to "broodrooster",
        "sink" to "gootsteen",
        "refrigerator" to "koelkast",
        "book" to "boek",
        "clock" to "klok",
        "vase" to "vaas",
        "scissors" to "schaar",
        "teddy bear" to "teddybeer",
        "hair drier" to "föhn",
        "toothbrush" to "tandenborstel"
    )
}

object LabelsEl {
    val MAP = mapOf(
        "person" to "άνθρωπος",
        "bicycle" to "ποδήλατο",
        "car" to "αυτοκίνητο",
        "motorcycle" to "μοτοσικλέτα",
        "airplane" to "αεροπλάνο",
        "bus" to "λεωφορείο",
        "train" to "τρένο",
        "truck" to "φορτηγό",
        "boat" to "βάρκα",
        "traffic light" to "φανάρι",
        "fire hydrant" to "κρουνός",
        "stop sign" to "πινακίδα στοπ",
        "parking meter" to "παρκόμετρο",
        "bench" to "παγκάκι",
        "bird" to "πουλί",
        "cat" to "γάτα",
        "dog" to "σκύλος",
        "horse" to "άλογο",
        "sheep" to "πρόβατο",
        "cow" to "αγελάδα",
        "elephant" to "ελέφαντας",
        "bear" to "αρκούδα",
        "zebra" to "ζέβρα",
        "giraffe" to "καμηλοπάρδαλη",
        "backpack" to "σακίδιο",
        "umbrella" to "ομπρέλα",
        "handbag" to "τσάντα",
        "tie" to "γραβάτα",
        "suitcase" to "βαλίτσα",
        "frisbee" to "φρίσμπι",
        "skis" to "σκι",
        "snowboard" to "σνόουμπορντ",
        "sports ball" to "μπάλα",
        "kite" to "χαρταετός",
        "baseball bat" to "ρόπαλο μπέιζμπολ",
        "baseball glove" to "γάντι μπέιζμπολ",
        "skateboard" to "σκέιτμπορντ",
        "surfboard" to "σανίδα σερφ",
        "tennis racket" to "ρακέτα τένις",
        "bottle" to "μπουκάλι",
        "wine glass" to "ποτήρι κρασιού",
        "cup" to "κούπα",
        "fork" to "πιρούνι",
        "knife" to "μαχαίρι",
        "spoon" to "κουτάλι",
        "bowl" to "μπολ",
        "banana" to "μπανάνα",
        "apple" to "μήλο",
        "sandwich" to "σάντουιτς",
        "orange" to "πορτοκάλι",
        "broccoli" to "μπρόκολο",
        "carrot" to "καρότο",
        "hot dog" to "χοτ ντογκ",
        "pizza" to "πίτσα",
        "donut" to "ντόνατ",
        "cake" to "τούρτα",
        "chair" to "καρέκλα",
        "couch" to "καναπές",
        "potted plant" to "γλάστρα",
        "bed" to "κρεβάτι",
        "dining table" to "τραπεζαρία",
        "toilet" to "τουαλέτα",
        "tv" to "τηλεόραση",
        "laptop" to "λάπτοπ",
        "mouse" to "ποντίκι",
        "remote" to "τηλεχειριστήριο",
        "keyboard" to "πληκτρολόγιο",
        "cell phone" to "κινητό",
        "microwave" to "φούρνος μικροκυμάτων",
        "oven" to "φούρνος",
        "toaster" to "τοστιέρα",
        "sink" to "νεροχύτης",
        "refrigerator" to "ψυγείο",
        "book" to "βιβλίο",
        "clock" to "ρολόι",
        "vase" to "βάζο",
        "scissors" to "ψαλίδι",
        "teddy bear" to "αρκουδάκι",
        "hair drier" to "σεσουάρ",
        "toothbrush" to "οδοντόβουρτσα"
    )
}

object LabelsHe {
    val MAP = mapOf(
        "person" to "אדם",
        "bicycle" to "אופניים",
        "car" to "מכונית",
        "motorcycle" to "אופנוע",
        "airplane" to "מטוס",
        "bus" to "אוטובוס",
        "train" to "רכבת",
        "truck" to "משאית",
        "boat" to "סירה",
        "traffic light" to "רמזור",
        "fire hydrant" to "ברז כיבוי",
        "stop sign" to "תמרור עצור",
        "parking meter" to "מדחן",
        "bench" to "ספסל",
        "bird" to "ציפור",
        "cat" to "חתול",
        "dog" to "כלב",
        "horse" to "סוס",
        "sheep" to "כבש",
        "cow" to "פרה",
        "elephant" to "פיל",
        "bear" to "דוב",
        "zebra" to "זברה",
        "giraffe" to "ג׳ירפה",
        "backpack" to "תרמיל",
        "umbrella" to "מטרייה",
        "handbag" to "תיק יד",
        "tie" to "עניבה",
        "suitcase" to "מזוודה",
        "frisbee" to "פריזבי",
        "skis" to "מגלשיים",
        "snowboard" to "סנובורד",
        "sports ball" to "כדור",
        "kite" to "עפיפון",
        "baseball bat" to "מחבט בייסבול",
        "baseball glove" to "כפפת בייסבול",
        "skateboard" to "סקייטבורד",
        "surfboard" to "גלשן",
        "tennis racket" to "מחבט טניס",
        "bottle" to "בקבוק",
        "wine glass" to "כוס יין",
        "cup" to "ספל",
        "fork" to "מזלג",
        "knife" to "סכין",
        "spoon" to "כף",
        "bowl" to "קערה",
        "banana" to "בננה",
        "apple" to "תפוח",
        "sandwich" to "סנדוויץ׳",
        "orange" to "תפוז",
        "broccoli" to "ברוקולי",
        "carrot" to "גזר",
        "hot dog" to "נקניקייה",
        "pizza" to "פיצה",
        "donut" to "דונאט",
        "cake" to "עוגה",
        "chair" to "כיסא",
        "couch" to "ספה",
        "potted plant" to "עציץ",
        "bed" to "מיטה",
        "dining table" to "שולחן אוכל",
        "toilet" to "שירותים",
        "tv" to "טלוויזיה",
        "laptop" to "מחשב נייד",
        "mouse" to "עכבר",
        "remote" to "שלט",
        "keyboard" to "מקלדת",
        "cell phone" to "טלפון",
        "microwave" to "מיקרוגל",
        "oven" to "תנור",
        "toaster" to "טוסטר",
        "sink" to "כיור",
        "refrigerator" to "מקרר",
        "book" to "ספר",
        "clock" to "שעון",
        "vase" to "אגרטל",
        "scissors" to "מספריים",
        "teddy bear" to "דובון",
        "hair drier" to "מייבש שיער",
        "toothbrush" to "מברשת שיניים"
    )
}

object LabelsHu {
    val MAP = mapOf(
        "person" to "ember",
        "bicycle" to "bicikli",
        "car" to "autó",
        "motorcycle" to "motor",
        "airplane" to "repülőgép",
        "bus" to "busz",
        "train" to "vonat",
        "truck" to "teherautó",
        "boat" to "hajó",
        "traffic light" to "közlekedési lámpa",
        "fire hydrant" to "tűzcsap",
        "stop sign" to "stop tábla",
        "parking meter" to "parkolóóra",
        "bench" to "pad",
        "bird" to "madár",
        "cat" to "macska",
        "dog" to "kutya",
        "horse" to "ló",
        "sheep" to "birka",
        "cow" to "tehén",
        "elephant" to "elefánt",
        "bear" to "medve",
        "zebra" to "zebra",
        "giraffe" to "zsiráf",
        "backpack" to "hátizsák",
        "umbrella" to "esernyő",
        "handbag" to "kézitáska",
        "tie" to "nyakkendő",
        "suitcase" to "bőrönd",
        "frisbee" to "frizbi",
        "skis" to "síléc",
        "snowboard" to "snowboard",
        "sports ball" to "labda",
        "kite" to "papírsárkány",
        "baseball bat" to "baseball ütő",
        "baseball glove" to "baseball kesztyű",
        "skateboard" to "gördeszka",
        "surfboard" to "szörfdeszka",
        "tennis racket" to "teniszütő",
        "bottle" to "üveg",
        "wine glass" to "borospohár",
        "cup" to "bögre",
        "fork" to "villa",
        "knife" to "kés",
        "spoon" to "kanál",
        "bowl" to "tál",
        "banana" to "banán",
        "apple" to "alma",
        "sandwich" to "szendvics",
        "orange" to "narancs",
        "broccoli" to "brokkoli",
        "carrot" to "répa",
        "hot dog" to "hot dog",
        "pizza" to "pizza",
        "donut" to "fánk",
        "cake" to "torta",
        "chair" to "szék",
        "couch" to "kanapé",
        "potted plant" to "cserepes növény",
        "bed" to "ágy",
        "dining table" to "étkezőasztal",
        "toilet" to "WC",
        "tv" to "tv",
        "laptop" to "laptop",
        "mouse" to "egér",
        "remote" to "távirányító",
        "keyboard" to "billentyűzet",
        "cell phone" to "telefon",
        "microwave" to "mikrohullámú sütő",
        "oven" to "sütő",
        "toaster" to "kenyérpirító",
        "sink" to "mosogató",
        "refrigerator" to "hűtő",
        "book" to "könyv",
        "clock" to "óra",
        "vase" to "váza",
        "scissors" to "olló",
        "teddy bear" to "plüssmaci",
        "hair drier" to "hajszárító",
        "toothbrush" to "fogkefe"
    )
}

object LabelsRo {
    val MAP = mapOf(
        "person" to "persoană",
        "bicycle" to "bicicletă",
        "car" to "mașină",
        "motorcycle" to "motocicletă",
        "airplane" to "avion",
        "bus" to "autobuz",
        "train" to "tren",
        "truck" to "camion",
        "boat" to "barcă",
        "traffic light" to "semafor",
        "fire hydrant" to "hidrant",
        "stop sign" to "indicator stop",
        "parking meter" to "parcometru",
        "bench" to "bancă",
        "bird" to "pasăre",
        "cat" to "pisică",
        "dog" to "câine",
        "horse" to "cal",
        "sheep" to "oaie",
        "cow" to "vacă",
        "elephant" to "elefant",
        "bear" to "urs",
        "zebra" to "zebră",
        "giraffe" to "girafă",
        "backpack" to "rucsac",
        "umbrella" to "umbrelă",
        "handbag" to "geantă",
        "tie" to "cravată",
        "suitcase" to "valiză",
        "frisbee" to "frisbee",
        "skis" to "schiuri",
        "snowboard" to "snowboard",
        "sports ball" to "minge",
        "kite" to "zmeu",
        "baseball bat" to "bâtă de baseball",
        "baseball glove" to "mănușă de baseball",
        "skateboard" to "skateboard",
        "surfboard" to "placă de surf",
        "tennis racket" to "rachetă de tenis",
        "bottle" to "sticlă",
        "wine glass" to "pahar de vin",
        "cup" to "cană",
        "fork" to "furculiță",
        "knife" to "cuțit",
        "spoon" to "lingură",
        "bowl" to "bol",
        "banana" to "banană",
        "apple" to "măr",
        "sandwich" to "sandviș",
        "orange" to "portocală",
        "broccoli" to "broccoli",
        "carrot" to "morcov",
        "hot dog" to "hot dog",
        "pizza" to "pizza",
        "donut" to "gogoașă",
        "cake" to "tort",
        "chair" to "scaun",
        "couch" to "canapea",
        "potted plant" to "plantă în ghiveci",
        "bed" to "pat",
        "dining table" to "masă",
        "toilet" to "toaletă",
        "tv" to "tv",
        "laptop" to "laptop",
        "mouse" to "mouse",
        "remote" to "telecomandă",
        "keyboard" to "tastatură",
        "cell phone" to "telefon",
        "microwave" to "cuptor cu microunde",
        "oven" to "cuptor",
        "toaster" to "prăjitor de pâine",
        "sink" to "chiuvetă",
        "refrigerator" to "frigider",
        "book" to "carte",
        "clock" to "ceas",
        "vase" to "vază",
        "scissors" to "foarfece",
        "teddy bear" to "ursuleț",
        "hair drier" to "uscător de păr",
        "toothbrush" to "periuță de dinți"
    )
}

object LabelsCs {
    val MAP = mapOf(
        "person" to "osoba",
        "bicycle" to "kolo",
        "car" to "auto",
        "motorcycle" to "motorka",
        "airplane" to "letadlo",
        "bus" to "autobus",
        "train" to "vlak",
        "truck" to "náklaďák",
        "boat" to "loď",
        "traffic light" to "semafor",
        "fire hydrant" to "hydrant",
        "stop sign" to "značka stop",
        "parking meter" to "parkovací automat",
        "bench" to "lavička",
        "bird" to "pták",
        "cat" to "kočka",
        "dog" to "pes",
        "horse" to "kůň",
        "sheep" to "ovce",
        "cow" to "kráva",
        "elephant" to "slon",
        "bear" to "medvěd",
        "zebra" to "zebra",
        "giraffe" to "žirafa",
        "backpack" to "batoh",
        "umbrella" to "deštník",
        "handbag" to "kabelka",
        "tie" to "kravata",
        "suitcase" to "kufr",
        "frisbee" to "frisbee",
        "skis" to "lyže",
        "snowboard" to "snowboard",
        "sports ball" to "míč",
        "kite" to "drak",
        "baseball bat" to "baseballová pálka",
        "baseball glove" to "baseballová rukavice",
        "skateboard" to "skateboard",
        "surfboard" to "surf",
        "tennis racket" to "tenisová raketa",
        "bottle" to "láhev",
        "wine glass" to "sklenka vína",
        "cup" to "hrnek",
        "fork" to "vidlička",
        "knife" to "nůž",
        "spoon" to "lžíce",
        "bowl" to "miska",
        "banana" to "banán",
        "apple" to "jablko",
        "sandwich" to "sendvič",
        "orange" to "pomeranč",
        "broccoli" to "brokolice",
        "carrot" to "mrkev",
        "hot dog" to "hot dog",
        "pizza" to "pizza",
        "donut" to "donut",
        "cake" to "dort",
        "chair" to "židle",
        "couch" to "pohovka",
        "potted plant" to "květináč",
        "bed" to "postel",
        "dining table" to "jídelní stůl",
        "toilet" to "toaleta",
        "tv" to "tv",
        "laptop" to "notebook",
        "mouse" to "myš",
        "remote" to "ovladač",
        "keyboard" to "klávesnice",
        "cell phone" to "telefon",
        "microwave" to "mikrovlnka",
        "oven" to "trouba",
        "toaster" to "toustovač",
        "sink" to "dřez",
        "refrigerator" to "lednička",
        "book" to "kniha",
        "clock" to "hodiny",
        "vase" to "váza",
        "scissors" to "nůžky",
        "teddy bear" to "méďa",
        "hair drier" to "fén",
        "toothbrush" to "kartáček"
    )
}

object LabelsBg {
    val MAP = mapOf(
        "person" to "човек",
        "bicycle" to "колело",
        "car" to "кола",
        "motorcycle" to "мотор",
        "airplane" to "самолет",
        "bus" to "автобус",
        "train" to "влак",
        "truck" to "камион",
        "boat" to "лодка",
        "traffic light" to "светофар",
        "fire hydrant" to "хидрант",
        "stop sign" to "знак стоп",
        "parking meter" to "паркомат",
        "bench" to "пейка",
        "bird" to "птица",
        "cat" to "котка",
        "dog" to "куче",
        "horse" to "кон",
        "sheep" to "овца",
        "cow" to "крава",
        "elephant" to "слон",
        "bear" to "мечка",
        "zebra" to "зебра",
        "giraffe" to "жираф",
        "backpack" to "раница",
        "umbrella" to "чадър",
        "handbag" to "чанта",
        "tie" to "вратовръзка",
        "suitcase" to "куфар",
        "frisbee" to "фризби",
        "skis" to "ски",
        "snowboard" to "сноуборд",
        "sports ball" to "топка",
        "kite" to "хвърчило",
        "baseball bat" to "бухалка",
        "baseball glove" to "ръкавица",
        "skateboard" to "скейтборд",
        "surfboard" to "сърф",
        "tennis racket" to "тенис ракета",
        "bottle" to "бутилка",
        "wine glass" to "чаша вино",
        "cup" to "чаша",
        "fork" to "вилица",
        "knife" to "нож",
        "spoon" to "лъжица",
        "bowl" to "купа",
        "banana" to "банан",
        "apple" to "ябълка",
        "sandwich" to "сандвич",
        "orange" to "портокал",
        "broccoli" to "броколи",
        "carrot" to "морков",
        "hot dog" to "хот-дог",
        "pizza" to "пица",
        "donut" to "поничка",
        "cake" to "торта",
        "chair" to "стол",
        "couch" to "диван",
        "potted plant" to "саксия",
        "bed" to "легло",
        "dining table" to "маса",
        "toilet" to "тоалетна",
        "tv" to "телевизор",
        "laptop" to "лаптоп",
        "mouse" to "мишка",
        "remote" to "дистанционно",
        "keyboard" to "клавиатура",
        "cell phone" to "телефон",
        "microwave" to "микровълнова",
        "oven" to "фурна",
        "toaster" to "тостер",
        "sink" to "мивка",
        "refrigerator" to "хладилник",
        "book" to "книга",
        "clock" to "часовник",
        "vase" to "ваза",
        "scissors" to "ножица",
        "teddy bear" to "мече",
        "hair drier" to "сешоар",
        "toothbrush" to "четка за зъби"
    )
}

object LabelsHr {
    val MAP = mapOf(
        "person" to "osoba",
        "bicycle" to "bicikl",
        "car" to "auto",
        "motorcycle" to "motor",
        "airplane" to "avion",
        "bus" to "autobus",
        "train" to "vlak",
        "truck" to "kamion",
        "boat" to "brod",
        "traffic light" to "semafor",
        "fire hydrant" to "hidrant",
        "stop sign" to "znak stop",
        "parking meter" to "parkirni automat",
        "bench" to "klupa",
        "bird" to "ptica",
        "cat" to "mačka",
        "dog" to "pas",
        "horse" to "konj",
        "sheep" to "ovca",
        "cow" to "krava",
        "elephant" to "slon",
        "bear" to "medvjed",
        "zebra" to "zebra",
        "giraffe" to "žirafa",
        "backpack" to "ruksak",
        "umbrella" to "kišobran",
        "handbag" to "torbica",
        "tie" to "kravata",
        "suitcase" to "kofer",
        "frisbee" to "frizbi",
        "skis" to "skije",
        "snowboard" to "snowboard",
        "sports ball" to "lopta",
        "kite" to "zmaj",
        "baseball bat" to "bejzbolska palica",
        "baseball glove" to "bejzbolska rukavica",
        "skateboard" to "skejt",
        "surfboard" to "daska za surfanje",
        "tennis racket" to "teniski reket",
        "bottle" to "boca",
        "wine glass" to "vinska čaša",
        "cup" to "šalica",
        "fork" to "vilica",
        "knife" to "nož",
        "spoon" to "žlica",
        "bowl" to "zdjela",
        "banana" to "banana",
        "apple" to "jabuka",
        "sandwich" to "sendvič",
        "orange" to "naranča",
        "broccoli" to "brokula",
        "carrot" to "mrkva",
        "hot dog" to "hot dog",
        "pizza" to "pizza",
        "donut" to "krafna",
        "cake" to "torta",
        "chair" to "stolica",
        "couch" to "sofa",
        "potted plant" to "biljka u tegli",
        "bed" to "krevet",
        "dining table" to "blagovaonski stol",
        "toilet" to "WC",
        "tv" to "tv",
        "laptop" to "laptop",
        "mouse" to "miš",
        "remote" to "daljinski",
        "keyboard" to "tipkovnica",
        "cell phone" to "telefon",
        "microwave" to "mikrovalna",
        "oven" to "pećnica",
        "toaster" to "toster",
        "sink" to "sudoper",
        "refrigerator" to "hladnjak",
        "book" to "knjiga",
        "clock" to "sat",
        "vase" to "vaza",
        "scissors" to "škare",
        "teddy bear" to "medo",
        "hair drier" to "sušilo za kosu",
        "toothbrush" to "četkica za zube"
    )
}

object LabelsSr {
    val MAP = mapOf(
        "person" to "особа",
        "bicycle" to "бицикл",
        "car" to "ауто",
        "motorcycle" to "мотор",
        "airplane" to "авион",
        "bus" to "аутобус",
        "train" to "воз",
        "truck" to "камион",
        "boat" to "брод",
        "traffic light" to "семафор",
        "fire hydrant" to "хидрант",
        "stop sign" to "знак стоп",
        "parking meter" to "паркомат",
        "bench" to "клупа",
        "bird" to "птица",
        "cat" to "мачка",
        "dog" to "пас",
        "horse" to "коњ",
        "sheep" to "овца",
        "cow" to "крава",
        "elephant" to "слон",
        "bear" to "медвед",
        "zebra" to "зебра",
        "giraffe" to "жирафа",
        "backpack" to "ранац",
        "umbrella" to "кишобран",
        "handbag" to "торбица",
        "tie" to "кравата",
        "suitcase" to "кофер",
        "frisbee" to "фризби",
        "skis" to "скије",
        "snowboard" to "сноуборд",
        "sports ball" to "лопта",
        "kite" to "змај",
        "baseball bat" to "бејзбол палица",
        "baseball glove" to "бејзбол рукавица",
        "skateboard" to "скејт",
        "surfboard" to "даска за сурфовање",
        "tennis racket" to "тениски рекет",
        "bottle" to "боца",
        "wine glass" to "винска чаша",
        "cup" to "шоља",
        "fork" to "виљушка",
        "knife" to "нож",
        "spoon" to "кашика",
        "bowl" to "чинија",
        "banana" to "банана",
        "apple" to "јабука",
        "sandwich" to "сендвич",
        "orange" to "наранџа",
        "broccoli" to "броколи",
        "carrot" to "шаргарепа",
        "hot dog" to "хот-дог",
        "pizza" to "пица",
        "donut" to "крофна",
        "cake" to "торта",
        "chair" to "столица",
        "couch" to "софа",
        "potted plant" to "биљка у саксији",
        "bed" to "кревет",
        "dining table" to "трпезаријски сто",
        "toilet" to "тоалет",
        "tv" to "тв",
        "laptop" to "лаптоп",
        "mouse" to "миш",
        "remote" to "даљински",
        "keyboard" to "тастатура",
        "cell phone" to "телефон",
        "microwave" to "микроталасна",
        "oven" to "рерна",
        "toaster" to "тостер",
        "sink" to "судопера",
        "refrigerator" to "фрижидер",
        "book" to "књига",
        "clock" to "сат",
        "vase" to "ваза",
        "scissors" to "маказе",
        "teddy bear" to "меда",
        "hair drier" to "фен за косу",
        "toothbrush" to "четкица за зубе"
    )
}

object LabelsSv {
    val MAP = mapOf(
        "person" to "person",
        "bicycle" to "cykel",
        "car" to "bil",
        "motorcycle" to "motorcykel",
        "airplane" to "flygplan",
        "bus" to "buss",
        "train" to "tåg",
        "truck" to "lastbil",
        "boat" to "båt",
        "traffic light" to "trafikljus",
        "fire hydrant" to "brandpost",
        "stop sign" to "stoppskylt",
        "parking meter" to "parkeringsautomat",
        "bench" to "bänk",
        "bird" to "fågel",
        "cat" to "katt",
        "dog" to "hund",
        "horse" to "häst",
        "sheep" to "får",
        "cow" to "ko",
        "elephant" to "elefant",
        "bear" to "björn",
        "zebra" to "zebra",
        "giraffe" to "giraff",
        "backpack" to "ryggsäck",
        "umbrella" to "paraply",
        "handbag" to "handväska",
        "tie" to "slips",
        "suitcase" to "resväska",
        "frisbee" to "frisbee",
        "skis" to "skidor",
        "snowboard" to "snowboard",
        "sports ball" to "boll",
        "kite" to "drake",
        "baseball bat" to "basebollträ",
        "baseball glove" to "basebollhandske",
        "skateboard" to "skateboard",
        "surfboard" to "surfbräda",
        "tennis racket" to "tennisracket",
        "bottle" to "flaska",
        "wine glass" to "vinglas",
        "cup" to "mugg",
        "fork" to "gaffel",
        "knife" to "kniv",
        "spoon" to "sked",
        "bowl" to "skål",
        "banana" to "banan",
        "apple" to "äpple",
        "sandwich" to "smörgås",
        "orange" to "apelsin",
        "broccoli" to "broccoli",
        "carrot" to "morot",
        "hot dog" to "varmkorv",
        "pizza" to "pizza",
        "donut" to "munk",
        "cake" to "tårta",
        "chair" to "stol",
        "couch" to "soffa",
        "potted plant" to "krukväxt",
        "bed" to "säng",
        "dining table" to "matbord",
        "toilet" to "toalett",
        "tv" to "tv",
        "laptop" to "laptop",
        "mouse" to "mus",
        "remote" to "fjärrkontroll",
        "keyboard" to "tangentbord",
        "cell phone" to "telefon",
        "microwave" to "mikrovågsugn",
        "oven" to "ugn",
        "toaster" to "brödrost",
        "sink" to "diskho",
        "refrigerator" to "kylskåp",
        "book" to "bok",
        "clock" to "klocka",
        "vase" to "vas",
        "scissors" to "sax",
        "teddy bear" to "nalle",
        "hair drier" to "hårtork",
        "toothbrush" to "tandborste"
    )
}
