package com.example.speedcam

/** COCO (80 sınıf) İngilizce etiket -> Türkçe karşılık. */
object TurkishLabels {
    private val map = mapOf(
        "person" to "İnsan",
        "bicycle" to "Bisiklet",
        "car" to "Araba",
        "motorcycle" to "Motosiklet",
        "airplane" to "Uçak",
        "bus" to "Otobüs",
        "train" to "Tren",
        "truck" to "Kamyon",
        "boat" to "Tekne",
        "traffic light" to "Trafik lambası",
        "fire hydrant" to "Hidrant",
        "stop sign" to "Dur tabelası",
        "parking meter" to "Parkmetre",
        "bench" to "Bank",
        "bird" to "Kuş",
        "cat" to "Kedi",
        "dog" to "Köpek",
        "horse" to "At",
        "sheep" to "Koyun",
        "cow" to "İnek",
        "elephant" to "Fil",
        "bear" to "Ayı",
        "zebra" to "Zebra",
        "giraffe" to "Zürafa",
        "backpack" to "Sırt çantası",
        "umbrella" to "Şemsiye",
        "handbag" to "El çantası",
        "tie" to "Kravat",
        "suitcase" to "Bavul",
        "frisbee" to "Frizbi",
        "skis" to "Kayak",
        "snowboard" to "Snowboard",
        "sports ball" to "Top",
        "kite" to "Uçurtma",
        "baseball bat" to "Beyzbol sopası",
        "baseball glove" to "Beyzbol eldiveni",
        "skateboard" to "Kaykay",
        "surfboard" to "Sörf tahtası",
        "tennis racket" to "Tenis raketi",
        "bottle" to "Şişe",
        "wine glass" to "Kadeh",
        "cup" to "Bardak",
        "fork" to "Çatal",
        "knife" to "Bıçak",
        "spoon" to "Kaşık",
        "bowl" to "Kâse",
        "banana" to "Muz",
        "apple" to "Elma",
        "sandwich" to "Sandviç",
        "orange" to "Portakal",
        "broccoli" to "Brokoli",
        "carrot" to "Havuç",
        "hot dog" to "Sosisli",
        "pizza" to "Pizza",
        "donut" to "Donut",
        "cake" to "Pasta",
        "chair" to "Sandalye",
        "couch" to "Kanepe",
        "potted plant" to "Saksı",
        "bed" to "Yatak",
        "dining table" to "Masa",
        "toilet" to "Klozet",
        "tv" to "TV",
        "laptop" to "Laptop",
        "mouse" to "Fare",
        "remote" to "Kumanda",
        "keyboard" to "Klavye",
        "cell phone" to "Telefon",
        "microwave" to "Mikrodalga",
        "oven" to "Fırın",
        "toaster" to "Tost makinesi",
        "sink" to "Lavabo",
        "refrigerator" to "Buzdolabı",
        "book" to "Kitap",
        "clock" to "Saat",
        "vase" to "Vazo",
        "scissors" to "Makas",
        "teddy bear" to "Oyuncak ayı",
        "hair drier" to "Saç kurutma",
        "toothbrush" to "Diş fırçası"
    )

    fun of(english: String?): String? {
        if (english == null) return null
        return map[english.lowercase()] ?: english
    }
}
